# Generated by Django 2.2.6 on 2019-11-06 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextflix_server_app', '0003_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='netflixmodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nextflix_server_app.UserModel'),
        ),
    ]
